seed: 42
dataset: cifar10
image_size: 224
pretrained: true

data_root: ./data
cache_dir: ./data/feature_cache

batch_size: 256
num_workers: 4
use_cuda: true

# In sklearn LogisticRegression, C is the inverse of L2 strength lambda.
logreg_c: 1.0

hydra:
  output_subdir: null
  run:
    dir: .
